# Generated by Django 4.1 on 2022-08-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROL_DESC', models.CharField(choices=[('Admin', 'Administrador'), ('Cliente', 'Cliente')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
    ]
