# Generated by Django 4.1 on 2022-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roles_alter_usuarios_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='ROL_DESC',
            field=models.CharField(choices=[(1, 'Administrador'), (2, 'Cliente')], max_length=25),
        ),
    ]
