# Generated by Django 4.1 on 2022-08-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_roles_rol_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
