# Generated by Django 4.1 on 2022-08-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuarios_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Direccion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Passwd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Tel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
