# Generated by Django 4.1 on 2022-08-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuarios_user_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
