# Generated by Django 4.1 on 2022-08-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuarios_user_rol_alter_usuarios_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Apellidos',
            field=models.CharField(default='Apellido', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Direccion',
            field=models.CharField(default='Ave direccion', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Email',
            field=models.EmailField(default='email@gmil.com', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Nombre',
            field=models.CharField(default='Nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Passwd',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Status',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='User_Tel',
            field=models.CharField(max_length=10),
        ),
    ]
