# Generated by Django 4.1 on 2022-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuarios_user_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
