# Generated by Django 4.1 on 2022-08-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usuarios_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.CharField(default='Cliente', max_length=25),
        ),
    ]
