# Generated by Django 4.1 on 2022-08-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usuarios_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='User_Rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
    ]
