# Generated by Django 4.1 on 2022-08-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roles_alter_usuarios_user_rol'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('NUMEROTRANSACCION', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('TRA_CUENTABANC', models.CharField(max_length=20)),
                ('TRA_TIPO', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='TC_DESC',
            field=models.CharField(choices=[('CC', 'Cuenta Corriente'), ('CCC', 'Cuenta con Chequera'), ('CA', 'Cuenta de Ahorro'), ('CN', 'Cuenta de Nómina'), ('CD', 'Cuenta en Dólares')], max_length=25),
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('NUMEROCUENTA', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CU_STATUS', models.CharField(max_length=1)),
                ('CU_CEDULACLI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios')),
                ('CU_TP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.tipocuenta')),
            ],
        ),
    ]
