# Generated by Django 4.1 on 2022-08-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_transacciones_alter_tipocuenta_tc_desc_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='CU_FECHAPERTURA',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='CU_SALDO',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='TRA_FECHA',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='TRA_MONTO',
            field=models.BigIntegerField(default=0),
        ),
    ]
