# Generated by Django 4.1 on 2022-08-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_cuentas_cu_fechapertura_cuentas_cu_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_CUENTABANC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas'),
        ),
    ]
