# Generated by Django 4.1 on 2022-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_transacciones_tra_cuentabanc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='CU_FECHAPERTURA',
            field=models.DateField(),
        ),
    ]
