# Generated by Django 4.1 on 2022-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuentas_cu_fechapertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_FECHA',
            field=models.DateField(),
        ),
    ]
