# Generated by Django 4.1 on 2022-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_cuentas_cu_cedulacli_alter_cuentas_cu_tp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='CU_SALDO',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='CU_STATUS',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
