# Generated by Django 4.1 on 2022-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_alter_cuentas_cu_saldo_alter_cuentas_cu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_CUENTABANC',
            field=models.CharField(max_length=20),
        ),
    ]
