# Generated by Django 4.1 on 2022-08-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_alter_transacciones_tra_cuentabanc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='NUMEROTRANSACCION',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
