# Generated by Django 4.1 on 2022-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_alter_transacciones_numerotransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='NUMEROTRANSACCION',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
