# Generated by Django 4.1 on 2022-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_alter_transacciones_numerotransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='NUMEROCUENTA',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='NUMEROTRANSACCION',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
