# Generated by Django 4.1 on 2022-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0017_alter_cuentas_numerocuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='NUMEROCUENTA',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
