# Generated by Django 4.1 on 2022-08-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0018_alter_cuentas_numerocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_FECHA',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_TIPO',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
