# Generated by Django 4.1 on 2022-08-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuarios_user_rol'),
        ('cuentas', '0019_alter_transacciones_tra_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='CU_CEDULACLI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios'),
        ),
    ]
