# Generated by Django 4.1 on 2022-08-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0020_alter_cuentas_cu_cedulacli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='CU_CEDULACLI',
            field=models.CharField(max_length=11),
        ),
    ]
