# Generated by Django 4.1 on 2022-08-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0021_alter_cuentas_cu_cedulacli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='NUMEROCUENTA',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
