# Generated by Django 4.1 on 2022-08-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0023_transacciones_tra_cedulacli'),
    ]

