# Generated by Django 4.1 on 2022-08-26 19:14

import aplicaciones.cuentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0024_transacciones_tra_balance'),
    ]

