# Generated by Django 4.1 on 2022-08-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0025_alter_transacciones_tra_balance'),
    ]

