# Generated by Django 4.1 on 2022-08-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuarios_user_rol'),
        ('cuentas', '0026_remove_transacciones_tra_balance'),
    ]
