# Generated by Django 4.1 on 2022-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0027_alter_transacciones_tra_cedulacli'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='TRA_CEDULACLI',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
