# Generated by Django 4.1 on 2022-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0028_transacciones_tra_cedulacli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='TRA_CEDULACLI',
            field=models.CharField(max_length=11),
        ),
    ]
